### ISSUE TITLE
Cachix isn't used when building the template configuration

### ISSUE THREAD

**Issue by loutr** [tstat/raspberry-pi-nix#8]
Hello! Just came across your project and I wanted to thank you for your nice work.

So, I've been trying to use it in the config of my RPi3B, but upon building I realised the cachix instance didn't provide the kernel package (6.1.63), which made the build quite endless.

I tried again building the default configuration provided in the readme, alone, and the exact same thing happened. Can someone confirm that the cache does or doesn't work?

Thanks

**Comment by RCMast3r** [comment]
I can confirm, I am running into the same issue.

**Comment by tstat** [comment]
Hello! In the past I have only pushed stuff to cachix when I cut a release, but I'm happy to push linux 6.1.63 to cachix now. I need to cut a new release soon, just need to dedicate some time to updating the readme and the example repo. 

I pushed linux 6.1.63 to cachix. Let me know if you run into any other trouble.

**Comment by RCMast3r** [comment]
hello! I just tried your example again and I ran into the issue again.

**Comment by RCMast3r** [comment]
Thank you so much for helping us with this! 

I swapped over to trying out your [example repo](https://github.com/tstat/raspberry-pi-nix-example) I have narrowed it down to my local setup not using the cache in the first place due to a trusted-users issue on my end (I am using the nix package manager on regular Ubuntu) as the `root` user and the user you are trying to add to the trusted-users list has to be in it. I swapped `extra-substituters` to `trusted-substituters` in an attempt to get around it but made it silently fail to pull from your cache. 

After fixing this issue I am happy to report that I am pulling everything from your cachix and I have a working nix build❤

**Comment by RCMast3r** [comment]
I can make a PR to add a blurb about this in your README if you would like

**Comment by tstat** [comment]
Ok great, glad you got it working. PRs improving the README are welcome.

**Comment by loutr** [comment]
Works like a charm for me too :)
